[project]
name = "vfuzztrie"
description = "Fuzzy prefix search implementation for Rust and Python."
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python"
]
dynamic = ["version"]
dependencies = [
    "fastuuid>=0.14.0",
]

[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[tool.maturin]
manifest-path = "rust/Cargo.toml"
python-source = "python"
module-name = "vfuzztrie._vfuzztrie"
features = ["pyo3/extension-module"]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
]
